---
- name: Install JDK 1.8
  apt:
    name: openjdk-8-jdk
    state: present

- name: Install Git
  apt:
    name: git
    state: present

- name: Create Maven download directory
  file:
    path: "{{ maven_home_parent_directory }}"
    state: directory
    mode: '0755'

- name: Check if Maven is already installed
  stat:
    path: "{{ maven_home_parent_directory }}/apache-maven-{{ maven_version }}"
  register: maven_installed

- name: Download Maven binaries
  get_url:
    url: "{{ maven_download_url }}"
    dest: "{{ maven_home_parent_directory }}/{{ maven_file_name }}"
  when: not maven_installed.stat.exists

- name: Extract Maven
  unarchive:
    src: "{{ maven_home_parent_directory }}/{{ maven_file_name }}"
    dest: "{{ maven_home_parent_directory }}"
    remote_src: yes
  when: not maven_installed.stat.exists

- name: Remove old Maven path config (if exists)
  file:
    path: /etc/profile.d/maven.sh
    state: absent
  when: not maven_installed.stat.exists

- name: Configure Maven environment variables
  lineinfile:
    dest: /etc/profile.d/maven.sh
    line: "{{ item.line }}"
    create: yes
    state: present
  with_items:
    - { line: "M2_HOME={{ maven_home_parent_directory }}/apache-maven-{{ maven_version }}" }
    - { line: "PATH=$PATH:$M2_HOME/bin" }
  when: not maven_installed.stat.exists

- name: Clean up Maven archive
  file:
    path: "{{ maven_home_parent_directory }}/{{ maven_file_name }}"
    state: absent
  when: not maven_installed.stat.exists
